version: '3.1'

services:
  postgres:
    restart: always
    image: postgres:15.3
    volumes:
      - ../db/postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_SUPER_USER_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    container_name: postgres-bayc

  rabbitmq:
    restart: always
    image: rabbitmq:3.11.16
    volumes:
      - ../lib/rabbitmq:/var/lib/rabbitmq
      - ../logs/rabbitmq:/var/log/rabbitmq
      - ../scripts/rabbitmq:/tmp/scripts
    hostname: "rabbitmq-bayc"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
      RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_DEFAULT_VHOST}"
    ports:
      - "${RABBITMQ_PORT}:5672"
    container_name: rabbitmq-bayc

  base:
    restart: always
    build:
      context: ../
    image: base-bayc
    volumes:
      - ../:/srv/bayc
    container_name: base-bayc
    working_dir: /srv/bayc
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DJANGO_SECRET_KEY=${DJANGO_SETTINGS_MODULE}
      - POSTGRES_SUPER_USER=${POSTGRES_SUPER_USER}
      - POSTGRES_SUPER_USER_PASSWORD=${POSTGRES_SUPER_USER_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - INFURA_URI=${INFURA_URI}
      - INFURA_API_KEY=${INFURA_API_KEY}
      - ABI_FILE=${ABI_FILE}
      - BAYC_CONTRACT_ADDRESS=${BAYC_CONTRACT_ADDRESS}